# Generated by Django 5.2.6 on 2025-09-14 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('order', models.SmallIntegerField(default=0, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Specialty',
                'verbose_name_plural': 'Specialties',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.CharField(max_length=191, unique=True, verbose_name='Teacher ID')),
                ('family_name', models.CharField(max_length=50, verbose_name='Family Name')),
                ('given_name', models.CharField(max_length=50, verbose_name='Given Name')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('RETIRED', 'Retired'), ('MOVED', 'Moved')], default='ACTIVE', max_length=20, verbose_name='Status')),
                ('id_card_number', models.CharField(max_length=191, unique=True, verbose_name='ID Card Number')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('email', models.EmailField(max_length=191, unique=True, verbose_name='Email')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, verbose_name='Gender')),
                ('phone_number', models.CharField(max_length=20, unique=True, verbose_name='Phone Number')),
                ('place_of_birth', models.TextField(blank=True, null=True, verbose_name='Place of Birth')),
                ('enrolled_date', models.DateField(verbose_name='Enrolled Date')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='teacher_profiles/', verbose_name='Profile Image')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.position', verbose_name='Position')),
                ('specialties', models.ManyToManyField(blank=True, to='teachers.specialty', verbose_name='Specialties')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User Account')),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
            },
        ),
    ]
