# Generated by Django 5.2.6 on 2025-10-03 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('order', models.SmallIntegerField(default=0, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'តួនាទី',
                'verbose_name_plural': 'តួនាទី',
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'ឯកទេស',
                'verbose_name_plural': 'ឯកទេស',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.CharField(max_length=191, unique=True, verbose_name='លេខសម្គាល់គ្រូ')),
                ('family_name', models.CharField(max_length=50, verbose_name='នាមត្រកូល')),
                ('given_name', models.CharField(max_length=50, verbose_name='នាមខ្លួន')),
                ('status', models.CharField(choices=[('ACTIVE', 'សកម្ម'), ('INACTIVE', 'អសកម្ម'), ('RETIRED', 'ចូលនិវត្តន៍'), ('MOVED', 'បានផ្លាស់ប្តូរ')], default='ACTIVE', max_length=20, verbose_name='ស្ថានភាព')),
                ('id_card_number', models.CharField(max_length=191, unique=True, verbose_name='លេខអត្តសញ្ញាណប័ណ្ណ')),
                ('date_of_birth', models.DateField(verbose_name='ថ្ងៃខែឆ្នាំកំណើត')),
                ('email', models.EmailField(max_length=191, unique=True, verbose_name='អ៊ីមែល')),
                ('gender', models.CharField(choices=[('Male', 'ប្រុស'), ('Female', 'ស្រី'), ('Other', 'ផ្សេងទៀត')], max_length=10, verbose_name='ភេទ')),
                ('phone_number', models.CharField(max_length=20, unique=True, verbose_name='លេខទូរស័ព្ទ')),
                ('place_of_birth', models.TextField(blank=True, null=True, verbose_name='ទីកន្លែងកំណើត')),
                ('enrolled_date', models.DateField(verbose_name='កាលបរិច្ឆេទចុះឈ្មោះ')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='teacher_profiles/', verbose_name='រូបភាពប្រវត្តិរូប')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.position', verbose_name='តួនាទី')),
                ('specialties', models.ManyToManyField(blank=True, to='teachers.specialty', verbose_name='ជំនាញ')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='គណនីអ្នកប្រើប្រាស់')),
            ],
            options={
                'verbose_name': 'គ្រូ',
                'verbose_name_plural': 'គ្រូបង្រៀន',
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='កាលបរិច្ឆេទចាប់ផ្តើម')),
                ('end_date', models.DateField(verbose_name='កាលបរិច្ឆេទបញ្ចប់')),
                ('reason', models.TextField(max_length=500, verbose_name='ហេតុផល')),
                ('status', models.CharField(choices=[('pending', 'រង់ចាំ'), ('approved', 'បានអនុម័ត'), ('rejected', 'បានបដិសេធ')], default='pending', max_length=10, verbose_name='ស្ថានភាព')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='បានបង្កើតនៅ')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to=settings.AUTH_USER_MODEL, verbose_name='អនុម័តដោយ')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='teachers.teacher', verbose_name='គ្រូ')),
            ],
            options={
                'verbose_name': 'សំណើច្បាប់ឈប់សម្រាក',
                'verbose_name_plural': 'សំណើច្បាប់ឈប់សម្រាក',
                'ordering': ['-created_at'],
            },
        ),
    ]
