# Generated by Django 5.2.6 on 2025-09-14 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='ឆ្នាំសិក្សា')),
                ('status', models.BooleanField(default=0, verbose_name='ស្ថានភាព')),
                ('start_date', models.DateField(verbose_name='ថ្ងៃចាប់ផ្តើម')),
                ('end_date', models.DateField(verbose_name='ថ្ងៃបញ្ចប់')),
            ],
            options={
                'verbose_name': 'ឆ្នាំសិក្សា',
                'verbose_name_plural': 'ឆ្នាំសិក្សា',
            },
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ប្រភេទថ្នាក់')),
            ],
            options={
                'verbose_name': 'ប្រភេទថ្នាក់',
                'verbose_name_plural': 'ប្រភេទថ្នាក់',
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='ឆមាស')),
                ('status', models.BooleanField(default=0, verbose_name='ស្ថានភាព')),
                ('start_date', models.DateField(verbose_name='ថ្ងៃចាប់ផ្តើម')),
                ('end_date', models.DateField(verbose_name='ថ្ងៃបញ្ចប់')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='core.academicyear', verbose_name='ឆ្នាំសិក្សា')),
            ],
            options={
                'verbose_name': 'ឆមាស',
                'verbose_name_plural': 'ឆមាស',
            },
        ),
    ]
