# Generated by Django 5.2.6 on 2025-10-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'អ្នកប្រើ', 'verbose_name_plural': 'អ្នកប្រើ'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'អ្នកគ្រប់គ្រង'), ('teacher', 'គ្រូបង្រៀន'), ('student', 'សិស្ស')], max_length=20, null=True),
        ),
    ]
