# Generated by Django 5.2.6 on 2025-09-17 16:01

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_schoolclass_students'),
        ('quizzes', '0001_initial'),
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentresponse',
            name='student_id',
        ),
        migrations.AddField(
            model_name='question',
            name='points',
            field=models.PositiveIntegerField(default=1, verbose_name='Points'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='classes',
            field=models.ManyToManyField(related_name='quizzes', to='classes.schoolclass', verbose_name='Assigned Classes'),
        ),
        migrations.AddField(
            model_name='studentresponse',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='quizzes.quiz', verbose_name='Quiz'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentresponse',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_responses', to='students.student', verbose_name='Student'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='Question Text'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='teachers.teacher', verbose_name='Teacher'),
        ),
        migrations.AlterField(
            model_name='studentresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='quizzes.question', verbose_name='Question'),
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(null=True, verbose_name='Score')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='Completed At')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quizzes.quiz', verbose_name='Quiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='students.student', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Quiz Attempt',
                'verbose_name_plural': 'Quiz Attempts',
            },
        ),
    ]
