# Generated by Django 5.2.6 on 2025-09-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_remove_studentresponse_student_id_question_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='start_time',
            field=models.DateTimeField(blank=True, help_text='When the quiz becomes available.', null=True, verbose_name='Start Time'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('RELEASE', 'Release'), ('PUBLISH', 'Publish'), ('ENDED', 'Ended')], default='DRAFT', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='time_limit',
            field=models.DurationField(blank=True, help_text='Time limit for the quiz (e.g., 30 minutes).', null=True, verbose_name='Time Limit'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Completed At'),
        ),
    ]
