# Generated by Django 5.2.6 on 2025-09-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_quiz_start_time_quiz_status_quiz_time_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='allow_check_answer',
            field=models.BooleanField(default=False, help_text='Allow students to view their answers after submission.', verbose_name='Allow Check Answer'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='allow_see_score',
            field=models.BooleanField(default=False, help_text='Allow students to see their score after submission.', verbose_name='Allow See Score'),
        ),
    ]
