# Generated by Django 5.2.6 on 2025-09-21 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_quiz_allow_check_answer_quiz_allow_see_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
