# Generated by Django 5.2.6 on 2025-09-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_quizattempt_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresponse',
            name='points_earned',
            field=models.FloatField(blank=True, null=True, verbose_name='Points Earned'),
        ),
    ]
