# Generated by Django 5.2.6 on 2025-09-17 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('courses', '0003_course_groups_studentcourseassignment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='groups',
        ),
        migrations.AddField(
            model_name='course',
            name='classes',
            field=models.ManyToManyField(blank=True, related_name='accessible_courses', to='classes.schoolclass', verbose_name='classes'),
        ),
    ]
