# Generated by Django 5.2.6 on 2025-10-03 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='កម្រិតថ្នាក់')),
            ],
            options={
                'verbose_name': 'កម្រិតថ្នាក់',
                'verbose_name_plural': 'កម្រិតថ្នាក់',
            },
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='ថ្នាក់')),
                ('order', models.PositiveIntegerField(blank=True, null=True, verbose_name='លំដាប់')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='classes.classlevel', verbose_name='កម្រិតថ្នាក់')),
                ('major', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.major', verbose_name='ប្រភេទថ្នាក់')),
                ('students', models.ManyToManyField(blank=True, related_name='school_classes', to=settings.AUTH_USER_MODEL, verbose_name='students')),
            ],
            options={
                'verbose_name': 'ថ្នាក់រៀន',
                'verbose_name_plural': 'ថ្នាក់រៀន',
            },
        ),
        migrations.CreateModel(
            name='HomeroomTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.ForeignKey(limit_choices_to={'status': True}, on_delete=django.db.models.deletion.CASCADE, related_name='homeroom_assignments', to='core.academicyear', verbose_name='ឆ្នាំសិក្សា')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeroom_assignments', to='teachers.teacher', verbose_name='គ្រូបន្ទុកថ្នាក់')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeroom_teachers', to='classes.schoolclass', verbose_name='ថ្នាក់')),
            ],
            options={
                'verbose_name': 'គ្រូបន្ទុកថ្នាក់',
                'verbose_name_plural': 'គ្រូបន្ទុកថ្នាក់',
                'unique_together': {('teacher', 'school_class', 'academic_year')},
            },
        ),
    ]
