# Generated by Django 5.2.6 on 2025-09-14 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='កម្រិតថ្នាក់')),
            ],
            options={
                'verbose_name': 'កម្រិតថ្នាក់',
                'verbose_name_plural': 'កម្រិតថ្នាក់',
            },
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='ថ្នាក់')),
                ('order', models.PositiveIntegerField(blank=True, null=True, verbose_name='លំដាប់')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='classes.classlevel', verbose_name='កម្រិតថ្នាក់')),
                ('major', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.major', verbose_name='ប្រភេទថ្នាក់')),
            ],
            options={
                'verbose_name': 'ថ្នាក់រៀន',
                'verbose_name_plural': 'ថ្នាក់រៀន',
            },
        ),
    ]
