# Generated by Django 5.2.6 on 2025-09-25 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_schoolclass_students'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeroomTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeroom_assignments', to='core.academicyear', verbose_name='ឆ្នាំសិក្សា')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeroom_teachers', to='classes.schoolclass', verbose_name='ថ្នាក់')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeroom_assignments', to=settings.AUTH_USER_MODEL, verbose_name='គ្រូបន្ទុកថ្នាក់')),
            ],
            options={
                'verbose_name': 'គ្រូបន្ទុកថ្នាក់',
                'verbose_name_plural': 'គ្រូបន្ទុកថ្នាក់',
                'unique_together': {('teacher', 'school_class', 'academic_year')},
            },
        ),
    ]
