# Generated by Django 5.2.6 on 2025-09-25 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_homeroomteacher'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeroomteacher',
            name='academic_year',
            field=models.ForeignKey(limit_choices_to={'status': True}, on_delete=django.db.models.deletion.CASCADE, related_name='homeroom_assignments', to='core.academicyear', verbose_name='ឆ្នាំសិក្សា'),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ឈ្មោះពេញ')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='អ៊ីមែល')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL, verbose_name='អ្នកប្រើប្រាស់')),
            ],
            options={
                'verbose_name': 'គ្រូ',
                'verbose_name_plural': 'គ្រូ',
            },
        ),
        migrations.AlterField(
            model_name='homeroomteacher',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeroom_assignments', to='classes.teacher', verbose_name='គ្រូបន្ទុកថ្នាក់'),
        ),
    ]
