# Generated by Django 5.2.6 on 2025-09-25 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_alter_homeroomteacher_academic_year_teacher_and_more'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeroomteacher',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeroom_assignments', to='teachers.teacher', verbose_name='គ្រូបន្ទុកថ្នាក់'),
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
