# Generated by Django 5.2.6 on 2025-10-03 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True, verbose_name='លេខសម្គាល់សិស្ស')),
                ('family_name', models.CharField(max_length=100, verbose_name='នាមត្រកូល')),
                ('given_name', models.CharField(max_length=100, verbose_name='នាមខ្លួន')),
                ('gender', models.CharField(choices=[('M', 'ប្រុស'), ('F', 'ស្រី')], max_length=1, verbose_name='ភេទ')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='ថ្ងៃខែឆ្នាំកំណើត')),
                ('place_of_birth', models.TextField(blank=True, null=True, verbose_name='ទីកន្លែងកំណើត')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='លេខទូរស័ព្ទ')),
                ('student_type', models.CharField(choices=[('ពេញម៉ោង', 'ពេញម៉ោង'), ('ក្រៅម៉ោង', 'ក្រៅម៉ោង')], max_length=20, verbose_name='ប្រភេទសិស្ស')),
                ('enrollment_date', models.DateField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទចុះឈ្មោះ')),
                ('major', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.major', verbose_name='ជំនាញ')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='គណនីប្រើប្រាស់')),
            ],
            options={
                'verbose_name': 'សិស្ស',
                'verbose_name_plural': 'សិស្ស',
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='ឈ្មោះឪពុក')),
                ('father_occupation', models.CharField(blank=True, max_length=100, null=True, verbose_name='មុខរបរឪពុក')),
                ('father_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='ទូរស័ព្ទឪពុក')),
                ('mother_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='ឈ្មោះម្ដាយ')),
                ('mother_occupation', models.CharField(blank=True, max_length=100, null=True, verbose_name='មុខរបរម្ដាយ')),
                ('mother_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='ទូរស័ព្ទម្ដាយ')),
                ('students', models.ManyToManyField(related_name='parents', to='students.student', verbose_name='សិស្ស')),
            ],
            options={
                'verbose_name': 'អាណាព្យាបាល',
                'verbose_name_plural': 'អាណាព្យាបាល',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'កំពុងរៀន'), ('TRANSFERRED', 'ផ្ទេរចេញ'), ('DROPOUT', 'បោះបង់'), ('GRADUATED', 'បញ្ចប់ការសិក្សា'), ('WITHDRAWN', 'ដកចេញ')], default='ACTIVE', max_length=50, verbose_name='ស្ថានភាពចុះឈ្មោះ')),
                ('enrolled_date', models.DateField(verbose_name='កាលបរិច្ឆេទចុះឈ្មោះ')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.academicyear', verbose_name='ឆ្នាំសិក្សា')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.schoolclass', verbose_name='ថ្នាក់')),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.semester', verbose_name='ឆមាស')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.student', verbose_name='សិស្ស')),
            ],
            options={
                'verbose_name': 'ការចុះឈ្មោះសិក្សា',
                'verbose_name_plural': 'ការចុះឈ្មោះសិក្សា',
                'unique_together': {('student', 'academic_year', 'semester')},
            },
        ),
    ]
